### PR TITLE
chore: this library does not depend on GAX

### PR DESCRIPTION
**Pull request by elharo**
@vam-google probably some old copy pasta

### CODE REVIEW

**Review by yihanzhen — APPROVED** [review]
LGTM (but I don't work this project any more so maybe wait for @vam-google to TAL)

**Review by vam-google — APPROVED** [review]
LGTM, @yihanzhen, @elharo  Yes, must be copypasta, as these classes used to be a part of gax.

**Review by elharo — COMMENTED** [review]
@chingor13 Minor internal cleanup but looks like we need a yoshi approver too

**Review by elharo — COMMENTED** [review]
go/friendly-ping

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
