### PR TITLE
chore: Use Java11 for release

### PR DESCRIPTION
**Pull request by lqiu96**
BEGIN_COMMIT_OVERRIDE
fix: Build with JDK11 and target JDK8
END_COMMIT_OVERRIDE

Error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project api-common: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

### CODE REVIEW

**Comment by suztomo** [comment]
Can you ensure the user of this library can use it with Java 8?

**Review by suztomo — CHANGES_REQUESTED** [review]
Ensure compatibility for Java 8 users.

I contributed to java-spanner in similar manner https://github.com/googleapis/java-spanner/pull/1870/files.

JAVA8_HOME and JAVA11_HOME are available.

**Comment by suztomo** [comment]
> Fatal error compiling: invalid flag: --release

This parameter should not be used when you're running in JDK 8.

**Comment by lqiu96** [comment]
Closing in favor of: https://github.com/googleapis/api-common-java/pull/420

**Comment by lqiu96** [comment]
We've decided to build with JDK11.

**Comment by lqiu96** [comment]
@suztomo @blakeli0 Can you re-review this whenever you get a chance?

**Comment by suztomo** [comment]
Can you test it in Java 8?

**Review by suztomo — APPROVED** [review]
The build Java 11 and running Java 8 test is already implemented

**Pull request merged**
